---
title: "R Notebook"
output: html_notebook
---
```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 <-
  as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地) -> 
storageLocations
```
```{r}
i<-1
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
allBorrowCount <- vector("numeric",18)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
i<-1
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i
```
```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```

```{r}
ans<-0
for(i in 1:10){
  newlyAdded<-i
  ans<-ans+newlyAdded
}
```

```{r}
libraryData$學號 %>% as.factor %>% levels -> student
studentBorrow <- vector("numeric", length(student))
for(i in c(1:length(student))){
student_i <- student[i]
numericalIndex <- which(libraryData$學號 == student_i)
studentSubsample_i <- libraryData[numericalIndex,]
studentBorrow_i <- nrow(studentSubsample_i)
studentBorrow[[i]] <- studentBorrow_i
}
```
```{r}
libraryData %>%
  mutate(
    學系=str_sub(學號,5,6)
    ##相當於 libraryData$學系 <-
#str_sub
  )
```

